### ISSUE TITLE
TFA Recovery tokens

### ISSUE THREAD

**Issue by IceDragon200** [polyfox/passport#3]
Passport should provide some modules for at least generating the tokens, as for storing it, we could leave that up to the user.

I was thinking of having a table dedicated to the recovery tokens though that could get bulky (seeing as we'd need around 10 to 20 tokens PER user)

Otherwise making use of postgres' array type, the tokens could be stored in a `{:array, :string}`, since the email & password combination is enough to find the user we can pop a recovery token from the array if available and save the record along with it's tracking updates.

@archSeer wdyt

**Comment by archseer** [comment]
Sure, just make sure those codes are one time use and that the user can trigger a regenerate
